[book]
authors = ["HuajingYu"]
language = "en"
multilingual = false
src = "src"
title = "Solidity Development Book"
description = "A book that teaches how to learn Solidity smart contracts."

[output.html]
curly-quotes = true
git-repository-url = "https://github.com/yuhuajing/solidity-book"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/yuhuajing/solidity-book/edit/main/{path}"
cname = "solidity-book.com"

[preprocessor.katex]
after = ["links"]
