[book]
authors = ["HuajingYu"]
language = "en"
multilingual = false
src = "src"
title = "Web3 Golang Development Book"
description = "A book that teaches how to learn web3 golang SDK."

[output.html]
curly-quotes = true
git-repository-url = "https://github.com/yuhuajing/web3-development-with-go-book"
git-repository-icon = "fa-github"
cname = "web3-golang--book.com"

[preprocessor.katex]
after = ["links"]
